### ISSUE TITLE
Misleading "CONVERTING A LIST TO JSON" description

### ISSUE THREAD

**Issue by 2colours** [lizmat/JSON-Fast-Hyper#1]
Hello,

I got confused when I set :!pretty to to-json. Now, reading the docs and the code carefully, I'm starting to think this is "not a bug but a feature", however, the description is somewhat misleading.

> When a list is converted to JSON, it will create a special hyperable version of JSON that is still completely valid JSON for all JSON parsers, but which can be interpreted in parallel when reading back. To allow this feature, the JSON will always be created as if the :pretty named argument has been specified as False.

This sounds as if the output of to-json on a Positional would always match the to-json output of JSON::Fast, with :!pretty. However, the JSON::Fast::Hyper version adds line breaks between elements - that's unlike JSON::Fast's :!pretty option - I assume this is what "special hyperable version of JSON" means.

I think this should be clarified in some way. For example:
- the :pretty option is disregarded
- the individual elements of the Positional are turned into json as if the :pretty option was set to False
- clarifying the means of "hyperable JSON", or, alternatively: "there shouldn't be any further assumptions about the prettifying of the output"

**Comment by lizmat** [comment]
Oops, this fell through the cracks  :-(

https://github.com/lizmat/JSON-Fast-Hyper/commit/be51220803c608f7b24e718c746b0b5cef637d45 fixes the description, will be in the next release.
